### ISSUE TITLE
Build against lower version of Framework

### ISSUE THREAD

**Issue by rojepp** [haf/expecto#177]
Is there any reason Expecto needs .Net 4.6.1? I ran against this trying to update dependencies for FSharp.Configuration, which is built against .Net 4.6, so latest Expecto can't be loaded.

**Comment by haf** [comment]
@rojepp Not something in particular. I just find it hard to know what framework to target when using mono because there's no tooling that tells me about what features of the very latest mono I cannot use when targeting lower frameworks. Also, afaik .Net standard 1.6 is mostly equivalent to 4.6, but I don't know about patch numbers.

Anyway; I normally let my test projects be the very latest version of everything using paket groups. Perhaps that's a nice solution in this case?

Otherwise, I don't mind PRs ;) – to remove the patch.

**Comment by haf** [comment]
I'm closing this, because it's not really a bug, it's more of a suggestion. If you send a PR I can merge that. 👍
