### ISSUE TITLE
first LogLevel is remembered in IRB session

### ISSUE THREAD

**Issue by fbehrens** [haf/expecto#21]
Hi, I often run my tests in `irb` like this:
```fsharp
#r"bin/release/wba.net.dll"
#load "../../tests/wba.test/Scripts/load-references-release.fsx"
#I "../../tests/wba.test"
open Expecto
open Swensen.Unquote

#load "convert.fs" "convert_test.fs" 
Wba.Test.Convert.test
|> runTests {defaultConfig with verbosity = Logging.LogLevel.Debug}
```
When I change the `LogLevel` to `Info` on subsequent runs, this will not reflect in the output (still `[dbg]` is logged, LogLevel of first run is remembered). 

I wondered about this behaviour, which seems to be so Non-functional. 

Is this intended, or why is that ? 

PS Please do not bother, I am a newbie, but eager to understand.

**Comment by haf** [comment]
Hi there

It's because of [this line](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L742) that only sets the configuration once. Its intention is that by default you get the literate console logger. But if you, from outside the library, override the logging, you'll get that overridden behaviour rather than that of the configuration structure passed to `runTests`.

Otherwise, an external initialisation of the logging wouldn't have an effect. It's easy to override though; just call `Expecto.Logging.Global.initialise` with a configuration record of your choice from the interactive.
