### ISSUE TITLE
Flaky mode

### ISSUE THREAD

**Issue by forki** [haf/expecto#31]
> After writing a number of UI tests, you’ll quickly notice that flakiness is a serious problem . One way we’re able to overcome this issue is by running failed tests multiple times.

    The flaky gem has a number of run modes:
      all tests - run everything
      from file - run a set of tests as specified in a text file
      one test - run only one test
      two pass - run tests once, then run only the failures x amount of times.

from https://appium.io/slate/en/tutorial/android.html#introduction36

I'm in the process of writing https://github.com/fsprojects/Canopy.Mobile and I wonder if such an automatic retry mode would be part of expecto or if it should be done in Canopy.Mobile

/cc @lefthandedgoat

**Comment by lefthandedgoat** [comment]
Not 100% sure how it is for mobile, but 9 out of 10 times a 'flaky' test in web is actually a bug in the website.  canopy/Canopy.Mobile will have stability built in to it for common stuff, like a control is not in the DOM/App yet, but is within a reasonable amount of time.

Example of root cause of a flaky test:

Test fails only occasionally, can't reproduce manually.
There are 2 web service calls, A and B.  B actually requires for A to finish before its 'on finished' event can fire and work correctly, but it is not coded this way.  A is faster than B so it almost always back first, and a bug does not show.  Rarely B will be faster than A and the bug shows.

If this bug happens 10% of the time, and you decide to simply rerun the test, the likely hood that it will fail two times in a row is ~1%, meaning you would never actually research it, despite it effecting end users 10% of the time.

Flaky mode may be a reasonable thing to add but almost always its not a reasonable things to use because it will mask bugs.  Besides, if you own the app under test, and the test, whats the likely hood that the flaky behavior is out of your control?

**Comment by forki** [comment]
I don't even get the https://github.com/fsprojects/Canopy.Mobile/blob/master/tests/Canopy.Mobile.Tests/SampleTests.fs suite rreliable. Just reduce timeout at https://github.com/fsprojects/Canopy.Mobile/blob/master/src/Canopy.Mobile/Canopy.Mobile.fs#L130 or use slower emulator.

**Comment by lefthandedgoat** [comment]
I will help you =)  It takes a butt load of time but its worth it in my opinion.  Your tests need to be trust worthy otherwise people will just blame them and they will be worthless.

**Comment by forki** [comment]
ok let's to solve it the right way

**Comment by lefthandedgoat** [comment]
After looking at the sleep you added its probably because you are clicking a button that causes a screen transition (don't have it working locally).

The right way to handle this is to put an assertion after the click, in your test, asserting that some element on that screen is shown.  That way you know that the screen has transitioned properly.

**Comment by forki** [comment]
Yeah probably. That's why we need you ;-)

Am 21.12.2016 6:03 nachm. schrieb "Chris Holt" <notifications@github.com>:

After looking at the sleep you added its probably because you are clicking
a button that causes a screen transition (don't have it working locally).

The right way to handle this is to put an assertion after the click, in
your test, asserting that some element on that screen is shown. That way
you know that the screen has transitioned properly.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/haf/expecto/issues/31#issuecomment-268576939>, or mute
the thread
