### ISSUE TITLE
Setup and teardown

### ISSUE THREAD

**Issue by forki** [haf/expecto#32]
SF: Also I wonder if test lists could contain setup and teardown code?
    
    @haf: It's possible. You could do some sketches of it and we can discuss. Another way is to use hole-in-the-middle factory functions like we do in the suave tests.
    
    SF: Holes sounds awesome. Go for it ;-)

I just thought about a different way:

```fsharp
    let tests =
        testList "android tests" [
            testList "session tests" [
                testCase "can get device UUID" <| fun () ->
                    ...

                testCase "can get dictionary data" <| fun () ->
                    ...
            ]

            testList "session tests 2" [
                testCase "can get device UUID" <| fun () ->
                    ...

                testCase "can get dictionary data" <| fun () ->
                    ...
            ]
        ]
```

How about providing "combinators" that inject setup and teardown.

```fsharp
    tests
    |> withTestSetup (fun () -> ....)        // before every test
    |> withTestTearDown (fun () -> ....) // after every test
    |> withTestListSetup (fun () -> ....)  // only at beginning of outer list
```

**Comment by forki** [comment]
I think flaky mode could be done like this as well: https://github.com/haf/expecto/issues/31

**Comment by mausch** [comment]
So @forki asked me to comment on this. 

I don't know exactly how much Expecto diverges from Fuchu but if the models are similar then the snippet above with the pipes won't generally work, because you'll want to reference values created in the Setup in your tests, instead of running Setup only for its side effects.
Similarly, you'll want to access values created in Setup in Teardown e.g. to dispose them.
So instead of this, you can apply setup/teardown with a simple higher-order function. I blogged about this in http://bugsquash.blogspot.com/2012/05/f-dsl-for-mbunit.html and wrote some sample code in https://github.com/mausch/Fuchu/blob/d59dc025a4cda5d192fe98167522713993de4e13/Fuchu.Tests/Tests.fs#L109-L145 . In particular, the last example there uses a helper function `testFixture` to apply a setup/teardown function to a list of tests.

As for a testlist setup, it can just be a lazy value.

Again, all of this applies to how I do things in Fuchu, I can't really comment much on Expecto.

**Comment by haf** [comment]
"f" is the "hole in the middle" in your example.

**Comment by haf** [comment]
Closing because I feel the question has been answered.
