### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by HurricanKai** [haf/expecto#391]
Is there any way of collecting code coverage?

**Comment by haf** [comment]
Maybe something like this? https://github.com/coverlet-coverage/coverlet#usage

If you follow the template, you'll have the SDK for tests referenced, and then `dotnet test` works with Expecto. Try it; it should work, since we're just calling into .Net.

**Comment by HurricanKai** [comment]
Hmm, I thought I tried that, but it didn't work. Will try again, maybe I did something wrong. Will report back, thanks

**Comment by haf** [comment]
I'm happy to look into it and make sure it works in return for payment of the time it takes me.

**Comment by baronfel** [comment]
Something similar is known to work. MiniScaffold has code coverage setup for expecto tests + AltCover (instead of coverlet), but the principles are the same. You need [test SDKs and the coverage tool](https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/Library/paket.dependencies#L8-L11), and then when you run tests you supply some [coverage parameters](https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/Library/build.fsx#L434-L439), and finally turn the output into [viewable reports](https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/Library/build.fsx#L449-L470)

**Comment by HurricanKai** [comment]
Hmm, all I get from codecov is
```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1594915816" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

**Comment by HurricanKai** [comment]
altcover has worked for me. Thanks :)
