### ISSUE TITLE
Activity/OpenTelemetry support

### ISSUE THREAD

**Issue by TheAngryByrd** [haf/expecto#496]
👋 Would y'all be open to adding Activity/OpenTelemetry  support in Expecto? I would usually wrap the tests in my own `testCase` but the main issue is it won't have the whole name since the test itself won't be a `FlatTest`. 

This wouldn't be adding any dependencies as ActivitySource/Activity is already in .net itself. I think adding an [ActivitySource](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource?view=net-8.0) to the `ExpectoConfig` and then using it in the `execTestAsync` would be the most straight forward approach.

Some resources to read:

- https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#activity
- https://www.jimmybogard.com/activitysource-and-listener-in-net-5/

**Comment by farlee2121** [comment]
First I want to make sure I'm understanding the underlying problem/motivations.
Could you elaborate on what problem you're facing and what the ideal outcome is?

**Comment by farlee2121** [comment]
If I'm understanding right, you want to add a trace or span to better group telemetry by test.
The reason you want to add it to the library instead of a custom extension (e.g. test fixture) is because you need access to the full test name.

If this is the case, I'm not opposed to the idea of adding open telemetry, but I also feel like access to the full test name is a more general problem that lots of extensions would want solved if we can solve it generally

**Comment by farlee2121** [comment]
For future readers, the conversation continued in PR #497

The general approach was to [map the test list with an open telemetry wrapper](https://github.com/TheAngryByrd/expecto/blob/40068a0db08e91811073bfdaa63b927e37aa35b3/Expecto.Tests/OpenTelemetry.fs#L163). This does have the downside that it doesn't centrally apply to tests discovered using reflection via `[<Tests>]`.
This is also a challenge for methods like shuffle and filter
