### ISSUE TITLE
Stress testing

### ISSUE THREAD

**Issue by AnthonyLloyd** [haf/expecto#79]
I'd like to propose a feature I'm interested in building and would welcome any feedback or suggestions.

It would be to add a command line switch like: --stress 02:00:00

This would run the parallel tests for 2 hours at full worker load adding a randomly picked test when a test finishes. FsCheck will need a bit of consideration as I think their `MaxTest` and `size` will need to be randomly picked.

The idea is that this will catch the following types of bugs:

- Memory leaks
- Threading bugs running same test at same time
- Rare threading bugs
- Rare property test fails

When the run finishes it will output the number of tests run and any fails (number and example by test) and stats on memory use.

I'd like to get started soon and will probably start after doing #68 in the next few days.

Possible follow up features:

- Save execution time, memory, gc statistics from the stress run timestamped
- Test for any major shift in these values to last run
- Load the latest stress test report to make a faster normal test run (order parallel tests by longest first, I think this can give up to ~25% max speed up)

**Comment by haf** [comment]
Agreed; it should be the time to spend that makes the test framework choose how to test, rather than the execution taking arbitrarily long causing developers to push down the number of tests run in order to get a fast feedback cycle.

I've also created https://github.com/haf/expecto/issues/81 which is directly relevant to this issue, because both property tests and interleaving of execution needs a framework that guides value generation and instrumentation, respectively.

I'd be delighted if you'd read my issue #81 and tell me what you think of it, too.

**Comment by haf** [comment]
Fixed with #86
