### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by agross** [haf/expecto#91]
Hi @haf,

Many thanks for creating Expecto! I'm just starting my first spare-time project with F# an decided to give it a try. I have to admit I'm still very much an F# noob, halfway through @isaacabraham's book.

Here are a couple of things I noticed:

1. Compiling the specs to an executable is awesome
1. As a noob I wonder why your advise on installing Expecto.BenchmarkDotNet and Expecto.FsCheck. Especially the latter -- why is it needed?
1. I'd like some more guidance around structuring tests. I started looking at https://github.com/haf/expecto/blob/master/Expecto.Sample/Expecto.Sample.fs and saw the whole shebang of what's possible. Some comments around the "blocks" of tests (e.g. `testList`) would be helpful. Especially, what's the diff between [`test`](https://github.com/haf/expecto/blob/master/Expecto.Sample/Expecto.Sample.fs#L51) and [`testCase`](https://github.com/haf/expecto/blob/master/Expecto.Sample/Expecto.Sample.fs#L48) here
1. Isaac's book shows how F# supports piping and how wonderfully clean the code gets. Coming from mspec and rspec I am used to define assertions fluently: `42.ShouldEqual(42)`, `42.should eq(42)`, `expect(42).to eq(42)`. With Expecto I tried
   ```fs
   42 |> Expect.equal 42 "These should equal"
   ```
    but the last arg is a string that I usually do not care about. No dice with piping the input. `Expect.equal x y` reminds me of my NUnit days with lots of Yoda-esque assertions.
1. I saw Expecto supports focused test. Excellent, I have been using that a lot with rspec. But as soon as I tried them Expecto being called from FAKE failed telling me there should not be any focused tests (I don't pass `--fail-on-focused-tests`)!

Thanks for listening :)

**Comment by forki** [comment]
I can answer the FAKE + focused tests part. Basically the idea was that
focused tests are used during development (usually temporary in IDE). So I
would consider it a mistake if someone commits focus flag and I want to let
the CI fail (otherwise it would only run one test and whole CI idea is
broken).

So fake sets the parameter by default and if you don't want that then you
need to opt out in the build script.

Am 06.02.2017 17:31 schrieb "Alexander Groß" <notifications@github.com>:

**Comment by haf** [comment]
Hello @agross and welcome to the F# world!

We're happy to have you here. To address your points:

 1. -
 2. It's not needed, only useful. I want to lower the barrier for people to write property based tests; this is one way to do it. Similarly, I think the world would be better if people relied more on statistically valid methods for testing performance, hence BenchmarkDotNet. Like you noted yourself, you don't have to install the ones you don't use, but it's useful to have property based and benchmark testing at your finger tips.
 3. Not sure how to answer this one; it's similar to Karma's and RSPec's and Mocha's `describe`. I tend to name lists with single- or two-word names and nest 2-3 levels to really make it clear what I focus on for a given set of tests. `test` is a workflow builder, so you use `{` to start the test and `}` to end it, whilst `testCase` takes a callback.
 4. The familiarity is intentional – I wanted people to get started quickly. But it's by no means the only way. Perhaps you could sketch out a module that tests fluently? I wrote a testing library in F# with the fluent syntax myself about 5 years back and the issue I had then was that the API wasn't discoverable. So my conclusion was this: having a fluent API with currying and 'slots' as its main design feature works if you write **a lot of** tests, otherwise you constantly have to refer to the documentation. Otherwise this style of assertions make the required runway shorter. But again; sketch out your ideas, we take PRs ;)
 5. Yes, FAKE needs to be told to accept focused tests, by design. You can also use the ionide runner, `CMD+SHIFT+P`, `Expecto: Run` to go around that.

**Comment by agross** [comment]
Hi guys,

Thank you for the feedback!

3. Alright, then I call `testList` a `context` from now on :)
4. [This helper](https://github.com/agross/watchr2/blob/master/source/Watchr.Specs/Helper.fs#L5) is what [I use](https://github.com/agross/watchr2/blob/master/source/Watchr.Specs/Ansi/Simple.fs#L12). Looks fluent to me.
5. Magic! I had some issues getting the VS Code runner to work, hence I always went back to the console to run FAKE. Makes total sense to forbid focused tests in the CI. // @forki
